<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260513112320 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE etablissement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, ville VARCHAR(255) NOT NULL, description TEXT NOT NULL, telephone VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, type VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE evenement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lieu VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, capacite INT NOT NULL, filiere_id INT NOT NULL, organisateur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B26681E180AA129 ON evenement (filiere_id)');
        $this->addSql('CREATE INDEX IDX_B26681ED936B2FA ON evenement (organisateur_id)');
        $this->addSql('CREATE TABLE filiere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, domaine VARCHAR(255) NOT NULL, description TEXT NOT NULL, duree INT NOT NULL, langue VARCHAR(100) NOT NULL, image VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE filiere_etablissement (filiere_id INT NOT NULL, etablissement_id INT NOT NULL, PRIMARY KEY (filiere_id, etablissement_id))');
        $this->addSql('CREATE INDEX IDX_6707593E180AA129 ON filiere_etablissement (filiere_id)');
        $this->addSql('CREATE INDEX IDX_6707593EFF631228 ON filiere_etablissement (etablissement_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, telephone VARCHAR(20) DEFAULT NULL, etablissement_id INT NOT NULL, filiere_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE INDEX IDX_8D93D649FF631228 ON "user" (etablissement_id)');
        $this->addSql('CREATE INDEX IDX_8D93D649180AA129 ON "user" (filiere_id)');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT FK_B26681E180AA129 FOREIGN KEY (filiere_id) REFERENCES filiere (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evenement ADD CONSTRAINT FK_B26681ED936B2FA FOREIGN KEY (organisateur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE filiere_etablissement ADD CONSTRAINT FK_6707593E180AA129 FOREIGN KEY (filiere_id) REFERENCES filiere (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE filiere_etablissement ADD CONSTRAINT FK_6707593EFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649FF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649180AA129 FOREIGN KEY (filiere_id) REFERENCES filiere (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE evenement DROP CONSTRAINT FK_B26681E180AA129');
        $this->addSql('ALTER TABLE evenement DROP CONSTRAINT FK_B26681ED936B2FA');
        $this->addSql('ALTER TABLE filiere_etablissement DROP CONSTRAINT FK_6707593E180AA129');
        $this->addSql('ALTER TABLE filiere_etablissement DROP CONSTRAINT FK_6707593EFF631228');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649FF631228');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649180AA129');
        $this->addSql('DROP TABLE etablissement');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('DROP TABLE filiere');
        $this->addSql('DROP TABLE filiere_etablissement');
        $this->addSql('DROP TABLE "user"');
    }
}
